spring:
  application:
    name:gateway
server:
  port: 8088
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/
    region: default
    registryFetchIntervalSeconds: 5
zuul:
  routes:
    hi-service:
      path:/**
      sensitive-headers:Set-Cookie,Authorization
hystrix:
  command:
    hi-service:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds:600000